public enum OpCode
{
    CHAT_MESSAGE = 1,
    SPAWN_PLAYER = 2,
    PLAYER_TRANSFORM = 3,
    START_GAME = 4,
    START_ROUND = 9,
    END_ROUND = 10,
    END_GAME = 5,
    REACHED_GOAL = 6,
    ACTIVATE_TRAP = 7,
    TELEPORT_PLAYER = 8,
    OPEN_BARRIERS = 11,
    CLOSE_BARRIERS = 12,
    JOIN_GAME = 13,
    LEAVE_GAME = 14,

}