@startuml
class InPause {
    + <<override>> OnEnter() : void
    + <<override>> OnExit() : void
    + <<override>> OnUpdate() : void
    + <<override>> OnFixedUpdate() : void
    + <<override>> OnLateUpdate() : void
}
PlayerMovement <|-- InPause
@enduml
