@startuml
class Net_OpenBarriers {
    + Net_OpenBarriers()
    + Net_OpenBarriers(reader:DataStreamReader)
    + Net_OpenBarriers(reader:DataStreamReader, deathRunGameLoop:DeathRunGameLoop)
    + <<override>> Serialize(writer:DataStreamWriter) : void
    + <<override>> ReceivedOnClient() : void
}
NetMessage <|-- Net_OpenBarriers
@enduml
