@startuml
enum OpCode {
    CHAT_MESSAGE= 1,
    SPAWN_PLAYER= 2,
    PLAYER_TRANSFORM= 3,
    START_GAME= 4,
    REACHED_GOAL= 5,
    ACTIVATE_TRAP= 6,
    TELEPORT_PLAYER= 7,
    OPEN_BARRIERS= 8,
    CLOSE_BARRIERS= 9,
    JOIN_GAME= 10,
    LEAVE_GAME= 11,
    PLAYER_GRAVITY= 12,
    PLAYER_DIED= 13,
    REACHED_CHECKPOINT= 14,
    PLAYER_DISCONNECT= 15,
}
@enduml
