@startuml
class FiniteStateMachine {
    + FiniteStateMachine(startState:BaseState, states:BaseState[])
    + OnUpdate() : void
    + OnFixedUpdate() : void
    + OnLateUpdate() : void
    + SwitchState(newStateStype:System.Type) : void
    + DebugCurrentState() : void
    + GetLastState() : BaseState
}
@enduml
